# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18jilsx2-xg2Jcg_1SjmJqdIxCefgOw7Y
"""

from sklearn.ensemble import RandomForestClassifier
def run_model(X_train, X_test, y_train):
    model= RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)[:, 1]
    else:
        y_prob = None

    return y_pred, y_prob
